apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: subscription-v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: subscription
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 20